name: Package and Push OCTGN Plugin to MyGet

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install NuGet CLI
        run: |
          curl -L https://dist.nuget.org/win-x86-commandline/latest/nuget.exe -o nuget.exe

      - name: Create .o8g file
        run: |
          mkdir -p build
          zip -r build/MageWars.o8g GameDatabase Template DeckBuilder -x "*.git*" "*.DS_Store"

      - name: Create .nuspec file
        run: |
          cat <<EOF > MageWars.nuspec
          <?xml version="1.0"?>
          <package>
            <metadata>
              <id>MageWars</id>
              <version>1.0.0</version>
              <authors>Curt</authors>
              <description>Mage Wars OCTGN plugin</description>
            </metadata>
            <files>
              <file src="build/MageWars.o8g" target="content/MageWars.o8g" />
            </files>
          </package>
          EOF

      - name: Pack NuGet package
        run: dotnet nuget pack MageWars.nuspec

      - name: Push to MyGet
        run: dotnet nuget push MageWars.1.0.0.nupkg --api-key ${{ secrets.MYGET_API_KEY }} --source https://www.myget.org/F/testfeed_simple/api/v2/package
